### ISSUE TITLE
Cant save product

### ISSUE THREAD

**Issue by webnut-de** [themexpert/digicom#111]
After click on save i get this error: 

1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 3 SQL=SELECT GROUP_CONCAT(id) as id FROM nf38digicom_products_bundle WHERE product_id=13 AND bundle_type='category' AND bundle_id NOT IN ()

**Comment by shamsbd71** [comment]
thanks, its already fixed.
