### ISSUE TITLE
Free Products - Price: 0

### ISSUE THREAD

**Issue by webnut-de** [themexpert/digicom#139]
This is not really an issue, but i would be nice to add products for free too. I cant save products with a price of zero right now. Will it be possible to add this feature?

Thx :smile_cat:

**Comment by shamsbd71** [comment]
@webnut-de 
thanks for using digicom
right now default price is empty, the one you can see is a placeholder like this : 00.00
So to make a product just input 0 as price
we will look forward to see others review to remove the placeholder and make the field blank to avoid confusion.

would you please let me know if its not working if you input 0 as price?
thanks

**Comment by webnut-de** [comment]
Yes, it works with 0. Nice! :smile: 
Thank you!

**Comment by shamsbd71** [comment]
you are welcome, we will remove placeholder on next release
