### ISSUE TITLE
Quantity

### ISSUE THREAD

**Issue by webnut-de** [themexpert/digicom#146]
I know digital products are mostly a single product, but sometimes its make sense to buy more than one.
So it would be nice to define if the product can handle quantity or not.
https://nimbus.everhelper.me/client/notes/share/261714/ZD4aCDRhDU7T3U5Tu19AEHudhLKvgd0N/

**Comment by codexpert** [comment]
DigiCom has this feature but its opt-out and you can enable it from Global Settings https://www.evernote.com/l/AFzM-53nVv1MJLQ2ZapxqREU04DPs6IWbGw

**Comment by webnut-de** [comment]
Found it! Thx! :)
