### ISSUE TITLE
RemoveFromCart - "event is not defined"

### ISSUE THREAD

**Issue by webnut-de** [themexpert/digicom#147]
The "RemoveFromCart" button dont work for me.

Console says:

ReferenceError: event is not defined
event.preventDefault();

**Comment by shamsbd71** [comment]
can you please provide details about it with screenshot?
and describe when it shows ? i have tested in few environment, nothing found like that :(

**Comment by webnut-de** [comment]
It always shows if click the "RemoveFromCart" Button:

Some Screenshots 
![bildschirmfoto 2015-08-06 um 11 58 23](https://cloud.githubusercontent.com/assets/12933331/9109005/ad424cd2-3c32-11e5-8442-0777657f6fcd.png)
![bildschirmfoto 2015-08-06 um 11 57 50](https://cloud.githubusercontent.com/assets/12933331/9109006/ad42ba78-3c32-11e5-8af4-fe5a32e68ab9.png)
![screenshot-www webnut de 2015-08-06 12-00-41](https://cloud.githubusercontent.com/assets/12933331/9109024/d814090a-3c32-11e5-85b4-e3c45c7a76d5.jpg)
