### ISSUE TITLE
Terms Modal is not working!

### ISSUE THREAD

**Issue by webnut-de** [themexpert/digicom#158]
"TypeError: jQuery(...).modal is not a function"

![bildschirmfoto 2015-08-07 um 09 14 21](https://cloud.githubusercontent.com/assets/12933331/9130630/cbc493ce-3ce4-11e5-9521-34f125295845.png)
![bildschirmfoto 2015-08-07 um 09 14 37](https://cloud.githubusercontent.com/assets/12933331/9130631/cbc86562-3ce4-11e5-8254-1a55c066d26e.png)

**Comment by shamsbd71** [comment]
issue resolved, but jquery and bootstrap is required for now
