### ISSUE TITLE
"Apply Discount on" remove button not work

### ISSUE THREAD

**Issue by webnut-de** [themexpert/digicom#160]
Again it is: 
ReferenceError: event is not defined
event.preventDefault();

![bildschirmfoto 2015-08-07 um 09 56 26](https://cloud.githubusercontent.com/assets/12933331/9131302/ae013f80-3cea-11e5-953d-c23780900a97.png)

**Comment by shamsbd71** [comment]
its fixed. bootstrap and jquery is required.
