### ISSUE TITLE
no terms alert

### ISSUE THREAD

**Issue by webnut-de** [themexpert/digicom#164]
If the terms are not checked, the submit button is disabled.
After click there is no alert that says that the user have to accept the terms. -> The user didnt know why he cant go to the next step.

**Comment by shamsbd71** [comment]
its been fixed.
the approach is:
if you click on checkout button it will show you an alert that you have to accept terms. if you select that checkout box, it wont show the alert instead it will go to next step.
btw, bootstrap is required.
