### ISSUE TITLE
Quantity not shown when logged in

### ISSUE THREAD

**Issue by webnut-de** [themexpert/digicom#167]
I buyed a product 30x. But that fact is point out nowhere.
In backend its ok.

![bildschirmfoto 2015-08-07 um 11 00 20](https://cloud.githubusercontent.com/assets/12933331/9132401/91391c16-3cf3-11e5-9395-6cd46f8d3cf9.png)
![bildschirmfoto 2015-08-07 um 10 59 14](https://cloud.githubusercontent.com/assets/12933331/9132402/913d15fa-3cf3-11e5-8c16-c52fd3d3a9cb.png)
![bildschirmfoto 2015-08-07 um 11 00 07](https://cloud.githubusercontent.com/assets/12933331/9132403/913e0c12-3cf3-11e5-97da-69f484260dc6.png)

**Comment by shamsbd71** [comment]
this issue already been fixed.
