### ISSUE TITLE
"Orders view" prices

### ISSUE THREAD

**Issue by webnut-de** [themexpert/digicom#169]
In the "Orders View" we have two prices: "Price" and "Total Paid". So "Price" is the single price?
In my example "Price" have to be "30 EUR", not "900 EUR".

![screenshot-www webnut de 2015-08-07 11-18-20](https://cloud.githubusercontent.com/assets/12933331/9132819/a1963096-3cf6-11e5-8c2e-4ace77fd4a06.jpg)
Fitting to that, it would be nice to show the quantity: #167

**Comment by shamsbd71** [comment]
Price is total payable price against that order, so if you purchase 30x n each 30, then its 900
:)
