### ISSUE TITLE
Product View backend missing <th>

### ISSUE THREAD

**Issue by webnut-de** [themexpert/digicom#174]
![bildschirmfoto 2015-08-09 um 11 37 08](https://cloud.githubusercontent.com/assets/12933331/9154371/71e9079c-3e8b-11e5-9441-fd243451141f.png)

**Comment by shamsbd71** [comment]
@webnut-de 
Please check it, i dont see anything like missing the table structure!!!

![image](https://cloud.githubusercontent.com/assets/1936565/9219711/a7061468-40fe-11e5-8829-d2af08e3181a.png)

**Comment by webnut-de** [comment]
@shamsbd71 
I checked it. Its not an missing <th>. Its an additional <td>

I found it in the products.php on line 218
```php
<?php if ($assoc) : ?>
<td class="hidden-phone">
	<?php if ($item->association) : ?>
		<?php echo JHtml::_('contentadministrator.association', $item->id); ?>
	<?php endif; ?>
</td>
<?php endif;?>
```
![screenshot-www webnut de 2015-08-12 10-33-49](https://cloud.githubusercontent.com/assets/12933331/9219908/ae12c0fa-40de-11e5-9448-18849b8f474a.jpg)

**Comment by shamsbd71** [comment]
@webnut-de thanks. i have single language only :+1:
