### ISSUE TITLE
Profile -> Name

### ISSUE THREAD

**Issue by webnut-de** [themexpert/digicom#192]
I guess it would be better to show the name value that is registered in joomla already in the profile setting.

Instead of
`<input name="name" type="text" id="name" size="30" value="<?php echo $cust->name ?>" />`

use
`<input name="name" type="text" id="name" size="30" value="<?php echo $user->name ?>" />`

**Comment by shamsbd71** [comment]
thanks for the suggestions, but we have plan to introduce guest checkout later, so we want to keep info separate and in general after login or register its already being used the joomla username as username and name as name

hope that helps

**Comment by webnut-de** [comment]
I think i need to explain it.

I'm a new user that already registers at my website (Just joomla registration, not digicom).
I put some products in my cart and went to checkout.
Now, i need to fill out the registration/profil form for digicom.
Isnt it better if the value of the name is the same like in joomla?
It can stored separate, but what im talking about is that it is "prefilled".
![screenshot-www webnut de 2015-08-18 15-38-32](https://cloud.githubusercontent.com/assets/12933331/9331425/bc63c286-45bf-11e5-8b74-9d476bcc7c90.jpg)

What i have done is to give digicom higher priority:

```php
if(!empty($cust->name)){
	$name = $cust->name;
}
elseif(!empty($user->name)) {
	$name = $user->name;
}
else
{
	$name = $cust->name;
}
```
`<input name="name" type="text" id="name" size="30" value="<?php echo $cust->name ?>" placeholder="<?php echo JText::_("COM_DIGICOM_NAME"); ?> *" />`
