### ISSUE TITLE
PayPal issues (Important!!!)

### ISSUE THREAD

**Issue by webnut-de** [themexpert/digicom#193]
1) Payment is still pending #179 
2 (Important!!) After paying the payment returns every few minutes!! Because of this issue i get a lot of mails, would be nice if you can stop this quickly :scream: 

![bildschirmfoto 2015-08-17 um 16 55 27](https://cloud.githubusercontent.com/assets/12933331/9307843/0a572290-4501-11e5-9d56-992df07496b8.png)

**Comment by shamsbd71** [comment]
Issue details:
1. paid amount added 2 times
i. once payment complete n paypal sent a confirmation
ii. second user click return to site

**Comment by codexpert** [comment]
I think you can do comment like this ;)

- [x] Issue One
- [ ] Issue two
