### ISSUE TITLE
Introtext in tag view

### ISSUE THREAD

**Issue by webnut-de** [themexpert/digicom#199]
If i insert "Read More" in the product description textarea, it has no effect on the tag view. It shows always the full text.

I know its "complicated" with the short description. Maybe it is useful to build a plugin that shows the shortdescription istead of the introtext in the "tag view"?!

**Comment by shamsbd71** [comment]
hey @webnut-de 
i'm sorry, according to our present structure plan and content map with joomla maping is set to use introtext. so we are not gonna change that now a days.

maybe later on based on demand we can consider it

thanks

**Comment by shamsbd71** [comment]
oh sorry i got you wrong! i'll handle it. the way it should be its not like that.
i just test it and know this

its not taking intro text

**Comment by webnut-de** [comment]
Nice! :)

Maybe my expression wasn't clear enough.
