### ISSUE TITLE
#1054 after summary

### ISSUE THREAD

**Issue by webnut-de** [themexpert/digicom#202]
I get this error after summary before it goes to payment.

`Fehler: 1054 Unknown column 'name' in 'field list' SQL=SELECT `name` FROM kdf23_digicom_customers WHERE id=62`

No matter what payment method i use.

**Comment by shamsbd71** [comment]
its update fail issue. seems database didnt update successfully

need to install update gradually, 
first beta 1
then beta 1 build 1
then beta 2

and how we are working on stable target and its finished with final task
now we are finalizing

and making hooks and plugins with it with migration
