### ISSUE TITLE
#1054 after save settings

### ISSUE THREAD

**Issue by webnut-de** [themexpert/digicom#203]
`Unknown column 'c.name' in 'field list' SQL=SELECT o.*, c.name FROM kdf23_digicom_orders o, kdf23_digicom_customers c WHERE `c`.`id`=`o`.`userid` AND `status` = "Active" ORDER BY `o`.`order_date` DESC LIMIT 5`

**Comment by shamsbd71** [comment]
its old script issue for update fails
will create another issue for this
Update from beta 1 error sql #216
