### ISSUE TITLE
Content Plugin wrong parameter on validity

### ISSUE THREAD

**Issue by webnut-de** [themexpert/digicom#204]
The content plugin shows "year" as validity instead of lifetime.

![screenshot-www webnut de 2015-08-19 11-39-57](https://cloud.githubusercontent.com/assets/12933331/9353325/c4e64dae-4667-11e5-8f4e-c94de811b372.jpg)

**Comment by shamsbd71** [comment]
its ok. basically its only field to store in database as settings
this expiration_type applied only when price_type != 0
