### ISSUE TITLE
Product View Event

### ISSUE THREAD

**Issue by shamsbd71** [themexpert/digicom#205]
Enable some event on product view
onaftertitle
onbeforetitle

onbeforeintro
onafterintro

onafterdisplayproduct

some events like this

**Comment by webnut-de** [comment]
Nice! Will it be possible to use some of the Joomla events like "onContentPrepare" and so on? That my  plugins and some others like the sigplus gallery will work with digicom too. :+1:

**Comment by shamsbd71** [comment]
onContentPrepare is already implemented :)

**Comment by webnut-de** [comment]
mmmh. Did you test it successfully?

At my installation my own plugin and sigplus gallery didnt work.

![screenshot-www webnut de 2015-08-21 10-26-40](https://cloud.githubusercontent.com/assets/12933331/9404371/40a4d770-47ef-11e5-82c6-de4e216b0e96.jpg)

**Comment by shamsbd71** [comment]
ya, its implemented i have tested it
~~~
$dispatcher->trigger('onContentPrepare', array ('com_digicom.product', &$item, &$this->params, $offset));
$item->text : contain both intro n full text
~~~

its working for me as i made a gallery plugin for digicom, its primary work done
i was testing to hook events

now sure why its not working for you?
but 
check your plugin for one thing
~~~
public function onContentPrepare($context, &$article, &$params, $page = 0)
	{

		$allowed_contexts = array('com_content.category', 'com_content.article', 'com_content.featured', 'mod_custom.content');


		if (!in_array($context, $allowed_contexts))
		{
			return true;
		}

~~~
so plugin did this allowed check and if it dosent match 
~~~
'com_digicom.product'
~~~
then it will bypass it
thanks

**Comment by webnut-de** [comment]
:( Still dont work for me. I tried your digicom content plugin. It also did not work in product view, but in modules!

![screenshot-www webnut de 2015-08-21 16-33-48](https://cloud.githubusercontent.com/assets/12933331/9410881/15a96386-4823-11e5-82a8-d23b83d75b5f.jpg)

**Comment by shamsbd71** [comment]
you were right, content plugin was working correct but we didn't print the output we receive from plugin

its implemented
thanks @webnut-de

**Comment by codexpert** [comment]
Done :)
