### ISSUE TITLE
Wrong link to product (if no itemid and SEF enabled)

### ISSUE THREAD

**Issue by webnut-de** [themexpert/digicom#209]
If a product is not forked with an itemid the link to that product in the cart ist linked into nowhere und i get a "404". Maybe its a SEF issue

**Comment by shamsbd71** [comment]
we will handle with it, but for sure you should have at least a menu item that refer to a category or products
:(

**Comment by shamsbd71** [comment]
for the time being you must have your products menu item, we will adapt new routing for digicom once joomla release new routing
