### ISSUE TITLE
Configuration -> click on "Close" Error

### ISSUE THREAD

**Issue by webnut-de** [themexpert/digicom#230]
`Unknown column 'c.name' in 'field list' SQL=SELECT o.*, c.name FROM kdf23_digicom_orders o, kdf23_digicom_customers c WHERE `c`.`id`=`o`.`userid` AND `status` = "Active" ORDER BY `o`.`order_date` DESC LIMIT 5 `

**Comment by shamsbd71** [comment]
this error bcs of not updated sequentially or update broke in the middle
though there was another incomplete issue i have fixed it

please knock me if you fail to update to latest version. but first install beta 2, then latest one.
