### ISSUE TITLE
Custom Template is not active?!

### ISSUE THREAD

**Issue by webnut-de** [themexpert/digicom#231]
My custom template is selected but nothing has changed in frontend. Only the default template is running.
It worked before updating to the pre-stable. 

![screenshot-www webnut de 2015-08-24 11-15-46](https://cloud.githubusercontent.com/assets/12933331/9436741/d20b3542-4a51-11e5-927b-51d16b23defa.jpg)

**Comment by shamsbd71** [comment]
new template procedure 
---
1. From digicom config select your template
2. if you want to change specific category n its root products template: then select template from category edit view and right side: change template
* this will override only category view, product view
* product bundle items has new separate layout called product_bundle.php

its checked and working now, previously it get override by parent category
