### ISSUE TITLE
Template Confusing

### ISSUE THREAD

**Issue by webnut-de** [themexpert/digicom#235]
If i choose my custom template in the Theme Options, the drop down shows the default one after saving. If i saved the default template it shows the custom template.

![screenshot-www webnut de 2015-08-24 15-44-30](https://cloud.githubusercontent.com/assets/12933331/9441605/65bb0590-4a77-11e5-9bd7-97526e6248fe.jpg)

**Comment by shamsbd71** [comment]
i never had this problem before and i checked didnt get any match.
can you help me figure this out?
thanks
![image](https://cloud.githubusercontent.com/assets/1936565/9467639/dcb7335c-4b5e-11e5-96bd-7816f4669d9a.png)

![image](https://cloud.githubusercontent.com/assets/1936565/9467648/f49255f6-4b5e-11e5-9e6b-b046b8938d8a.png)

**Comment by webnut-de** [comment]
I checked it again. After login all seems to be right. The bug arise after select a template and save the settings. Than the select field shows a different one than the active.

**Comment by shamsbd71** [comment]
in gitter i have attached a zip file, install the latest one and see if its gone.

**Comment by webnut-de** [comment]
its still there :(

custom is selected
default is shown

**Comment by webnut-de** [comment]
I made a freshly install to check if some problems creeped in while updating.
This one still exists.

![screenshot-www webnut de 2015-08-26 09-40-05](https://cloud.githubusercontent.com/assets/12933331/9487997/c929d790-4bd6-11e5-9c73-1cc16b728e4c.jpg)

**Comment by webnut-de** [comment]
Okay, after the fresh install my custom template ist load with the issue above, but products always show the default one!
I changed the template in the category without any result.
I renamed the default folder now, to get it to work.

**Comment by webnut-de** [comment]
Seems to work in 1.0. so i close it.
