### ISSUE TITLE
Feature Request: Based on #237 

### ISSUE THREAD

**Issue by webnut-de** [themexpert/digicom#240]
#237

I think it would be better to have this as a setting which the user can change?! Maybe it is an option that the user can control this for each product? Ex. I have some products that i sell as a single product and some where you can choose the quantity. Right know i check the product and make it dispay or not.

**Comment by codexpert** [comment]
@webnut-de we discussed this issue a lot. Real world scenario is for 'digital product', people doesn't put any quantity on product page. You can always change the quantity on cart page though.

Having feature while creating product will create more confusion, you know less option less confusion :)

**Comment by shamsbd71** [comment]
@webnut-de we have plan to introduce attributes
it will allow you to give options and price based on each attribs

hope you will enjoy it.
and one more thing:
did you notice we have an option to load extra fields from your override joomla template?
there is a file called attribs.sample.xml, remove the .sample from the name and edit a product
enjoy

**Comment by webnut-de** [comment]
@codexpert Yes, you're right. I think i'll adapt it the way i want...
@shamsbd71 Sounds great! I searched for attribs.sample.xml but cant find it. Can you give me a hint?

**Comment by shamsbd71** [comment]
install the latest one from gitter chat, i have attached one file for testing

**Comment by webnut-de** [comment]
Mmmh... i changed the file name, but dont know where to finde these extra fields?!

**Comment by shamsbd71** [comment]
look at this file
```
site/components/com_digicom/templates/default/attribs.sample.xml
```
if you have these template override from your joomla template then the file path will be
```
site/templates/your_template/html/com_digicom/templates/default/attribs.sample.xml
```
or if you select any alternative template from digicom config, then check template folder and find the file

rename it to 
```
attribs.xml
```
now go to digicom product manager, open any product or edit any existing one
bingo!!!
you have a new that there called Attributes

**Comment by webnut-de** [comment]
Sorry, it did not work for me :(

I use the alternative template.
I renamed the xml to: `attribs.xml`

The code is:
```xml
<?xml version="1.0" encoding="utf-8"?>
<form>
  <fields name="attribs" label="COM_DIGICOM_PRODUCT_ATTR_TITLE">
    <fieldset name="basic" label="COM_DIGICOM_PRODUCT_ATTR_TITLE">

      <field name="sample"
        type="text"
        description="Test Desc"
        label="Test"
        />
      <field name="sample2"
        type="text"
        description="Test Desc"
        label="Test"
        />
    </fieldset>

  </fields>
</form>
```
No attr. are loaded?!

![screenshot-www webnut de 2015-08-26 10-07-40](https://cloud.githubusercontent.com/assets/12933331/9488458/878683a2-4bda-11e5-8b7d-58133661d732.jpg)

**Comment by codexpert** [comment]
Please use GitHub as issue tracker and keep your discussion on chat room or forum. I'm closing this issue now.
