### ISSUE TITLE
"After adding item take user" Cant change to "To Cart"

### ISSUE THREAD

**Issue by webnut-de** [themexpert/digicom#269]
After save it always changed to "PopUp".

![screenshot-www webnut de 2015-09-18 11-24-55](https://cloud.githubusercontent.com/assets/12933331/9956364/6e7b6c3a-5df8-11e5-9763-8898bcbec9c9.jpg)

**Comment by shamsbd71** [comment]
please clear cache, it seems your cache issue. else it should work correct.

**Comment by webnut-de** [comment]
Yes, its an old cache issue. I close it.
