### ISSUE TITLE
add attribs into product.php

### ISSUE THREAD

**Issue by webnut-de** [themexpert/digicom#270]
Pls add the attributes into the product.php.
Right now there is no output.

$attribs  = json_decode($this->item->attribs);
foreach($attribs as $attr) {}

**Comment by codexpert** [comment]
We will add this to our documentation instead of code as its totally optional

**Comment by shamsbd71** [comment]
docs added
https://github.com/themexpert/digicom/wiki/_How-to-extend-DigiCom-from-core
https://github.com/themexpert/digicom/wiki/_How-to-show-DigiCom-extended-fields-value
