### ISSUE TITLE
Coupon issue

### ISSUE THREAD

**Issue by webnut-de** [themexpert/digicom#276]
First Image:
Coupon is added, everything is ok.

Second Image:
I changed the amount and it calculates the price on the item by the coupon, what is wrong.

Third Image: 
After page-refresh, the price is ok.

![bildschirmfoto 2015-09-22 um 15 47 19](https://cloud.githubusercontent.com/assets/12933331/10020079/484fa570-6141-11e5-8398-f72988f27ca6.png)
![bildschirmfoto 2015-09-22 um 15 47 29](https://cloud.githubusercontent.com/assets/12933331/10020081/485067da-6141-11e5-9d4f-0f4baa5d2a49.png)
![bildschirmfoto 2015-09-22 um 15 47 33](https://cloud.githubusercontent.com/assets/12933331/10020080/484fc046-6141-11e5-99a7-286785b1f42b.png)

**Comment by shamsbd71** [comment]
Hello
i have tested it, found its working correct.

can you see your console and let us know the error if there is any?

![image](https://cloud.githubusercontent.com/assets/1936565/10040176/2034e2ca-61fb-11e5-92c5-8a3b91544eb4.png)

**Comment by webnut-de** [comment]
No Error. I tryed it with the defaut template now. Seems like its a template bug, sry.
