### ISSUE TITLE
promocode on product - calculation confusion

### ISSUE THREAD

**Issue by webnut-de** [themexpert/digicom#277]
Its the same in the default template. If i have a promocode based on a product i'll get that confusing calcuation:
![screenshot-www webnut de 2015-09-23 14-37-09](https://cloud.githubusercontent.com/assets/12933331/10045223/51fe5e7a-6201-11e5-9b3c-65d00735d8ad.jpg)

I think it would be better not to subtract the promocode from the productitem. Its enough to subtract it after the summary, what do you think?

**Comment by shamsbd71** [comment]
Issue fixed this way
1. if promo for product then this way
![image](https://cloud.githubusercontent.com/assets/1936565/10173155/acb21732-6704-11e5-9d49-3bf52372a592.png)

2. if promo for cart this way
![image](https://cloud.githubusercontent.com/assets/1936565/10173204/d52a3320-6704-11e5-9b6e-a435046a8dbc.png)

and yes you were right, there was bug on discount for multi quantity.
all the bugs fixed for this and thanks :+1:  @webnut-de
