### ISSUE TITLE
Cart Module - Not loaded language strings

### ISSUE THREAD

**Issue by webnut-de** [themexpert/digicom#280]
Hi, I found another thing. If i use the cart module and the active page is not digicom, the language files are not loaded.

https://files.gitter.im/webnut-de/NgUA/Bildschirmfoto-2015-09-24-um-17.01.16.png

**Comment by shamsbd71** [comment]
I have tried to inspect the issue, what i found is you have used the code in module we didnt use. we used to show validity on cart or modal. not in module. so we didnt include them in module language file

if you want to modify the code to show the validity in module need to find a solution
or we will think about it @codexpert

**Comment by shamsbd71** [comment]
@webnut-de please replay this topic so we can close the issue or can know your opinion. thanks

**Comment by webnut-de** [comment]
I understand. It's not as bad as all that. I'll handle it with language overrites.

**Comment by shamsbd71** [comment]
thanks, closing the issue
