### ISSUE TITLE
Backend - Dashboard counts promocodes as sale

### ISSUE THREAD

**Issue by webnut-de** [themexpert/digicom#281]
Promocodes are not earning, or did i mixup something?

![screenshot-www webnut de 2015-09-24 21-19-52](https://cloud.githubusercontent.com/assets/12933331/10084161/41432b22-6302-11e5-9822-b58fe288f2e7.jpg)

**Comment by webnut-de** [comment]
This appears if the status is pendig. After changing the payment status, it is calcuated correctly. The 3 EUR are subtracted now.
![screenshot-www webnut de 2015-09-24 21-26-49](https://cloud.githubusercontent.com/assets/12933331/10084329/27822ffc-6303-11e5-8912-ccb47efb0d5c.jpg)

**Comment by shamsbd71** [comment]
@webnut-de  thanks for the issue, it was one of the major bug though its small fix. fixed already.
thanks again
