### ISSUE TITLE
Checkout redirection Issue

### ISSUE THREAD

**Issue by ahmedeshaan** [themexpert/digicom#310]
So I wanted checkout view to have menu, left and right modules. I created a new menu type from the checkout view, added the modules but still didn't see the menu selection. I noticed the url was messed up. &amp;. Looked up problem, it's caused by the jRoute function. I changed cart.php line 430, added false... $this->setRedirect(JRoute::_("index.php?option=com_digicom&view=checkout&id=".$order_id, false));

**Comment by shamsbd71** [comment]
@ahmedeshaan  can you tell me which file `cart.php` is, i searched for that like but its no in the model nor template ?

please mansion your digicom version

**Comment by shamsbd71** [comment]
changed applied it was on cart controller. thanks
