### ISSUE TITLE
Activate bundle package paid offline Payment method does not work

### ISSUE THREAD

**Issue by leoalv** [themexpert/digicom#311]
After paying with Offline Payment method. To activate the product with any method, this does not add the products to downloads

**Comment by shamsbd71** [comment]
hi @leoalv 
thanks for your interest in digicom. i didnt understand this pert `To activate the product with any method`

let me tell you the procedure to activate any order. go to your site admin > digicom > orders > select order and change status.

for offline payment : this is the only way to active an order.

please join us in gitter chat

**Comment by leoalv** [comment]
that's exactly what I did. I activated from Admin > Digicom > Orders and Admin > Digicom > Orders > ORDER_ID. but to go to the download area no downloadable files the newly activated bundle

**Comment by leoalv** [comment]
The problem happened at local server, remote hosting works perfect
