### ISSUE TITLE
Move and remove a client to a user group

### ISSUE THREAD

**Issue by leoalv** [themexpert/digicom#312]
By default customers belong to the registered users.

I have 3 periods of expiry of products 6 months, 1 year and lifetime. I would like you to purchase products from 6 months to move that customer user group 6Months and remove it passes 6 months. And so on with others expiration periods.

This would be useful to provide material support or customized support groups while they are active.

**Comment by codexpert** [comment]
We already did that for us(ThemeXpert site) and hoping to release as add-on soon.
