### ISSUE TITLE
Administrator User (ACL)

### ISSUE THREAD

**Issue by alebak** [themexpert/digicom#316]
When an Administrator User (ACL) enter to DigiCom extension, by default can't enter to the settings of the extension but the Administrator user if can. Please check the ACL features in your DigiCom menu.

![digicom - administrator_user_acl_options](https://cloud.githubusercontent.com/assets/6515879/12044070/9f38df18-ae59-11e5-90da-12ef136667ab.png)
![digicom - settings_menu_options](https://cloud.githubusercontent.com/assets/6515879/12044073/a86953e2-ae59-11e5-84ef-faa83d04b595.png)

**Comment by shamsbd71** [comment]
hi, your screenshoots says your digicom version either not installed correctly or not latest. please update it or reinstall it

and please provide the error details a bit more. thanks

**Comment by shamsbd71** [comment]
seems issue doesn't exist. if you have update please post again. thanks
