### ISSUE TITLE
Delete the product cart

### ISSUE THREAD

**Issue by carosouza** [themexpert/digicom#329]
Hello, I am testing the component and if you put a product in the cart, but not logged in, I can not, for example, delete the product cart, how to fix it?
Obs .: the standard menu DIGICOM is enabled with all options: Downloads, Orders, Profile, Cart.

Joomla 3.4.8
Didicom 1.2.5
PHP 5.4.45

**Comment by shamsbd71** [comment]
hi
sorry your issue is not clear, can you explain it better with some image? 

thanks for your interest and take time to make an issue. 
thanks

**Comment by shamsbd71** [comment]
hi,
i'm closing the issue as dont see any problem to remove cart items and its not clear completely. 
Please feel free to update again if you think its not solve yet.

thanks
