### ISSUE TITLE
Guest unable to register before purchasing

### ISSUE THREAD

**Issue by Sulpher** [themexpert/digicom#336]
Guest visitor want to buy an item, click on "add to cart" button and then unable to proceed to the next page since they need to log in first. but there is no link at registration page in the component.
Please see this animated screenshot: https://www.dropbox.com/s/ryicv8rxf4ub0p5/digicom.gif?dl=0

I tested Digicom 1.2.5 on Joomla 3.4.8 and Joomla 3.5 and it seems you missed something in the layout at checkout page.

**Comment by shamsbd71** [comment]
Hi @Sulpher 
thanks for the gif image :D 
ok, the thing is joomla has an option in user manager that allow you to enable registration. 

you need to enable that :)

**Comment by Sulpher** [comment]
Ah, yes... I did not notice that! :-D 
Now I see registration form is appeared in the tab. 

@shamsbd71, thanks for the hint ;-)
The request can be declined.
