### ISSUE TITLE
Cannot remove item from Cart

### ISSUE THREAD

**Issue by michalip** [themexpert/digicom#338]
hello
version digicom 1.3 on Joomla 3.5.1

**Steps to reproduce**

1. Add any item to cart (1 item)
2. view cart
3. Press remove item 
4. nothing will happen
5. Press check out ----> get the message that cart is empty

here is a test site http://cyprusaerialphoto.com/shopcap

thanks

**Comment by shamsbd71** [comment]
Hi
please come in gitter chat and provide you details, because it ok at our end and cant figure out the issue until we check it

thanks

**Comment by michalip** [comment]
Closing issue as I have disabled caching and I also saw that with the new releases caching is addressed....which helps a lot
