### ISSUE TITLE
Unable to add a product to bundle

### ISSUE THREAD

**Issue by webchun** [themexpert/digicom#359]
Hi guys, I'm unable to add single product to bundle. A bug?
http://imgur.com/a/15xFn

**Comment by webchun** [comment]
adding category to bundle is working just fine

**Comment by shamsbd71** [comment]
@webchun thanks for the issue, i'll check and fix.

**Comment by shamsbd71** [comment]
Sorry, in latest release i didnt find anything like this. please provide some details info so we can check,

thanks

**Comment by shamsbd71** [comment]
Closing this issue as we cant figure it out. please post some details if you still have this issue.
