### ISSUE TITLE
Paypal problem in version 1.3.4

### ISSUE THREAD

**Issue by davsevon** [themexpert/digicom#364]
After update to latest version of Digicom verison 1.3.4 the Paypal checkout halts in pop up for redirecting to Paypal.
My solution was that I replaced the plugin files with older version 1.3.3 and the redirect started to work again. 

Also in both 1.3.3 and 1.3.4 version I get a progress bar type is not defined error in js script. (could be local theme problem).

**Comment by shamsbd71** [comment]
Hi thanks @davsevon 
I'll check them :)

**Comment by shamsbd71** [comment]
its fixed
