### ISSUE TITLE
Joomla Update System

### ISSUE THREAD

**Issue by webchun** [themexpert/digicom#366]
Considering all extensions listed in JED will need to use Joomla Update system starting from [10 Jan 2017](https://extensions.joomla.org/support/knowledgebase/item/joomla-update-system-requirement), do you have any guidelines to implement this with digicom?

**Comment by shamsbd71** [comment]
Hello @webchun 
thanks for your concern about auto update the extension and maintaining the standard Joomla guideline.

> **You will feel happy to know that Digicom support Joomla auto update system from its beginning. so you can update through Joomla extension manager with one click** 💯
