### ISSUE TITLE
[Feature Request]  - Create Free download file option 

### ISSUE THREAD

**Issue by daromeo** [themexpert/digicom#368]
Please is possible to insert free download option in order to transform Add to Basket button in Download button ?

Best regards
Daniele

**Comment by shamsbd71** [comment]
Hi @daromeo 
Yes its possible through a plugin. But in core, there is no such option. You can contribute that or contact me in gitter chat to make that for you. :)

thanks

**Comment by daromeo** [comment]
There are costs for plugin or for your time? Please tell me that so I can
decide and evaluate. Best regards

Il 29 ott 2016 06:30, "Abu-Huraira" <notifications@github.com> ha scritto:

**Comment by shamsbd71** [comment]
Hi, sorry couldn't reply. please contact us at support@themexpert.com
