### ISSUE TITLE
downloads security

### ISSUE THREAD

**Issue by LALAU-POA** [themexpert/digicom#371]
Is there any way to see how many downloads were made of each purchase and their ips? to check security

**Comment by LALAU-POA** [comment]
If someone passes the login and password to other people, the admin can see it

**Comment by LALAU-POA** [comment]
i tried other plugin and his have this feature look the image
![da](https://cloud.githubusercontent.com/assets/23413461/20243260/55c2c63a-a937-11e6-9481-851645ed075a.jpg)

**Comment by shamsbd71** [comment]
We are making a plugin like this. you may contact us.
