### ISSUE TITLE
download manager

### ISSUE THREAD

**Issue by LALAU-POA** [themexpert/digicom#372]
Using digicom, why when I try to download a file (using download manager), it downloads the login.php or register.php instead of asking for a login and password, why?

**Comment by shamsbd71** [comment]
Hi @LALAU-POA 
The way you are asking it require server configuration and we dont deal with it :)

ok, to let you know, digicom doesn't support direct download through download manager. only once you login and your session is active you can download your file.

> You can make a third party plugin to use our digicom event and bypass this process. So users can download using those links.

as files path or usr is not absolute and authentication is one of the major priority, we did it that way. 

thanks

**Comment by LALAU-POA** [comment]
Sorry I'm only the owner of a website, I have no knowledge about the subject, login protection and password are fundamental, so is it impossible to use download manager? Or paying someone could you do it for me?

**Comment by shamsbd71** [comment]
We will introduce remote file storage late. that can help you.
For now we stream the files gradually, else files get broken when its large. 

i hope you get it.
thanks
