### ISSUE TITLE
Id session

### ISSUE THREAD

**Issue by gui8515** [themexpert/digicom#373]
Hello, how do I get the ID session in Digicom

I would like to do integration with seblod

[![Sem título.png](https://s18.postimg.org/n5f4skk55/Sem_t_tulo.png)](https://postimg.org/image/64w8jw73p/)

https://s18.postimg.org/n5f4skk55/Sem_t_tulo.png

**Comment by shamsbd71** [comment]
hi @gui8515 
There is a class for digicom session `DigiComSiteHelperSession` just call it like this:
```php
$session = new DigiComSiteHelperSession();
$sid = $session->_sid;
```
From digicom component you can call this class from anywhere but if you try to load it from outside digicom component, use this code:

```php
JLoader::discover('DigiComSiteHelper', JPATH_ROOT . '/components/com_digicom/helpers');
```

thanks
