### ISSUE TITLE
Profile checking

### ISSUE THREAD

**Issue by codexpert** [themexpert/digicom#38]
Can't finish my purchases - system inform that address is not correct - but when I try to indicate my correct address, zip code is not accepted (in brazilian format 09130-010)

**Comment by betools** [comment]
Additional info: when trying edit my infos in user dashboard panel, zip code stills not accepted.
Trying with 0913010 or 09130-010 but don't work

And I can't indicate my state addres...  select box show worng values as in image attached.
State fiels only shows Brazil and Sergipe...  but Brazil is the country, and we have 25 states here, not only Sergipe.

![problem_states_country](https://cloud.githubusercontent.com/assets/5460729/6881240/7fd25990-d535-11e4-9d55-bed621a1410e.jpg)
