### ISSUE TITLE
Product Settings is not working

### ISSUE THREAD

**Issue by swopnil** [themexpert/digicom#382]
### Steps to reproduce the issue

The submenu to menu leading to single product "Product Settings" is not working at all. Tested disabling options but with no luck. I had to enter product.php to digicom template and remove the parts i didn't need.
![product-setting](https://cloud.githubusercontent.com/assets/3949434/23539817/d7476a9a-0007-11e7-940c-b31e36adc44c.jpg)

**Comment by shamsbd71** [comment]
Thanks, removed those unnecesary options and added fews.
