### ISSUE TITLE
Digicom fail to manage a subscription with more than 3 digits price

### ISSUE THREAD

**Issue by swopnil** [themexpert/digicom#383]
### Steps to reproduce the issue
If i use a price per year and the price is over 1000 euro then the Digicom will add the product with price 1€.
That is a serious bug easily reproduced.

I will have to change my prices to 6 months plans to work.

**Comment by steinsson** [comment]
I have the same problem. I'm working with prices in the Icelandic Krona (there are around 120 to the Euro) so the pricetags tend to stretch up to 4 or 5 digits. Is anyone working on a fix for this?

**Comment by shamsbd71** [comment]
Its already fixed, waiting for next release. just finishing up one by one.

thanks
