### ISSUE TITLE
DIGICOM PRODUCTS CATALOGUE WITHOUT FREE OR PRICE

### ISSUE THREAD

**Issue by swopnil** [themexpert/digicom#386]
Hi guys,

I've just installed digistore quickstart because I want to make a technical products web, so I don't need cart or prices.

As you can see in screenshots, I've configurated catalog mode, but in products appears the next:

If you insert 50 dollars in the product price, it appears 50$ in the frontend.
If you insert 0 dollars in the product price, it appears FREE text.
If you erase the amount, it appears FREE text too.

How can I erase FREE text or amount?

If it could be, I would like that in the FREE text box it would appear the category, or an icon or image. Is this possible?

Thanks and regards

![digi-setting](https://cloud.githubusercontent.com/assets/3949434/23741039/ad77c58e-04d0-11e7-8d9a-27d3b29c44fe.jpg)
![digi-pro-setting](https://cloud.githubusercontent.com/assets/3949434/23741081/f16e166c-04d0-11e7-86d8-52c262b698f0.jpg)

**Comment by shamsbd71** [comment]
HI,
Free is coming from language file, you can change it to anything you like from language manager > override.

I have implemented the option to auto hide price in catalog mode.
