### ISSUE TITLE
 DIGICOM PRODUCTS CATALOGUE WITHOUT FREE OR PRICE

### ISSUE THREAD

**Issue by swopnil** [themexpert/digicom#387]
Hi guys,

I've just installed digistore quickstart because I want to make a technical products web, so I don't need cart or prices.

As you can see in screenshots, I've configurated catalog mode, but in products appears the next:

If you insert 50 dollars in the product price, it appears 50$ in the frontend.
If you insert 0 dollars in the product price, it appears FREE text.
If you erase the amount, it appears FREE text too.

How can I erase FREE text or amount?

If it could be, I would like that in the FREE text box it would appear the category, or an icon or image. Is this possible?

Thanks and regards
![screenhunter_35 mar 08 16 28](https://cloud.githubusercontent.com/assets/3949434/24229789/9629c8de-0fa5-11e7-97cf-15123b0d941d.jpg)
![screenhunter_36 mar 08 16 29](https://cloud.githubusercontent.com/assets/3949434/24230072/45ca7f62-0fa7-11e7-959d-4db24dcb6250.jpg)
![screenhunter_37 mar 08 16 33](https://cloud.githubusercontent.com/assets/3949434/24230079/524b6706-0fa7-11e7-8ac6-ee7e0a5dbf80.jpg)

**Comment by shamsbd71** [comment]
Hi
I have added options to hidesidebar, can turn on/off anyof the info or can control others.
will release soon and you can test.

thanks
