### ISSUE TITLE
offline payment feature request

### ISSUE THREAD

**Issue by infogatel2** [themexpert/digicom#389]
### Steps to reproduce the issue
The field "Description" in offline plugin won't show

### Expected result
It would be great to show the field "Description" to the user providing more information about offline payment such as bank account details

### Additional comments
Thank you in advance

**Comment by shamsbd71** [comment]
Its already there: go to plugin settings, filter by folder: digicom_pay. select Offline payment:
There you are . fill up details area with instruction to pay.

thanks
