### ISSUE TITLE
You must provide at least one recipient email address

### ISSUE THREAD

**Issue by infogatel2** [themexpert/digicom#390]
### Steps to reproduce the issue
When client is at the offline payment page

### Expected result
There should have no warning as no action has been taken yet

### Actual result
A message appears on top "You must provide at least one recipient email address"

**Comment by hypeitinc** [comment]
I'm getting the same thing but when checking out using PayPal.
Joomla 3.7.2 tried both PHP7 and 5.6
Don't know if it's related but even though the orders get processed and set to active they are not connected to the customer, so the customers order screen shows no orders.
The processing goes through with PayPal bot paying and receiving.

**Comment by hypeitinc** [comment]
Regarding the error message - I might have found the problem. In my case I had not filled out the email addresses for "cancel order" and "refund order" email recipients.

**Comment by shamsbd71** [comment]
Issue fixed, in next release you will have it.
thanks
