### ISSUE TITLE
Cart is empty after select offline payment

### ISSUE THREAD

**Issue by infogatel2** [themexpert/digicom#391]
### Steps to reproduce the issue
Selecting products and then offline payment

### Expected result
The product should remain in cart even if user navigates to another menu

### Actual result
The products dissapear from cart and then when user returns gets message "Cart is empty" 

### Additional comments
This issue is not applicable until a user select the offline payment method

**Comment by shamsbd71** [comment]
When you proceed from payment processor selection, order get placed. so after an older placed your card is empty. please publish the Digicom Toolber module for users to see there orders.

thanks
