### ISSUE TITLE
Bitcoin Payment Gateway

### ISSUE THREAD

**Issue by mertsuslu** [themexpert/digicom#396]
Is it possible to add a new payment gateway for Bitcoin ?
Like Bitpay.com, Blockchain.info Payment API ?

**Comment by shamsbd71** [comment]
Yes, its possible to add any third-party payment gateway support. In core, we will not add this support. thanks

**Comment by mertsuslu** [comment]
Is it possible to create a custom payment plugin related (blockchain.info API) for me ?
Thanks.

**Comment by shamsbd71** [comment]
yes possible. please join our gitter chat and message me: https://gitter.im/themexpert/digicom

thanks
