### ISSUE TITLE
Menu problem with root category

### ISSUE THREAD

**Issue by betools** [themexpert/digicom#40]
I can't point a menu button to root category - internal categories work fine in this menu type button, only root don't work. When linked to 'root category' only shows a error in frontend.

**Comment by shamsbd71** [comment]
hi @betools 
thanks for the report. Can you please share the screen shoot or error details. Bcs i cant see the error here.

**Comment by codexpert** [comment]
Everything working except when i select type 'Bundle'. It through error http://cl.ly/image/2E3S2p150547

```
If difficulties persist, please contact the System Administrator of this site and report the error below.
0 The image file does not exist.
```

**Comment by codexpert** [comment]
When i change order to `Title Reverse..` and `Category manager` frontend showing same error msg.

**Comment by betools** [comment]
Hi shamsbd71 the error occur when I try to point a menu item (quickstart used for test comes with the error) to 'root category'.

If I point to sub-category, works fine.
See attached images please
![backend_config_rootcategory](https://cloud.githubusercontent.com/assets/5460729/6880947/6e777ac6-d527-11e4-9b18-2ad740047a69.jpg)
![frontend_error_rootcategory](https://cloud.githubusercontent.com/assets/5460729/6880948/732f35b8-d527-11e4-853f-9b74718152c1.jpg)
