### ISSUE TITLE
Product not found when adding to cart

### ISSUE THREAD

**Issue by Howliee** [themexpert/digicom#403]
### Steps to reproduce the issue
Go to the store page and choose a product to add to the cart

### Expected result
Product gets added to the cart

### Actual result
404 page informing that the product was not found

### Additional comments
I'm developing this site for a client and need this finished asap. I have looked into the issue myself but so far I cannot find a solution to the problem or what may be causing it.

medalmad.developmy.co.uk

**Comment by shamsbd71** [comment]
hi @Howliee,
thanks for reporting back. we are going to attend JoomlaDayKL17 tomorrow. i'll get back to you later. thanks

**Comment by Howliee** [comment]
Hi Sham,

Just wondering if you've had the chance to take a look at this issue for me.

Cheers

**Comment by Howliee** [comment]
I managed to solve the issue myself and for anyone else who have run into this problem here's my solution:

`<form name="prod" class="form" id="product-form" action="<?php echo JRoute::_('index.php?option=com_digicom&view=cart');?>" method="post" style="width:100%;">`

The JRoute on the form action overrides the actual URL so removing the JRoute gives the proper URL:

`<form name="prod" class="form" id="product-form" action="/index.php?option=com_digicom&view=cart" method="post" style="width:100%;">`
