### ISSUE TITLE
Problem with Fixed Validity for Products

### ISSUE THREAD

**Issue by leoalv** [themexpert/digicom#410]
### Steps to reproduce the issue
Add new product or change product validity to fixed, add  validity (days, monts or years) and Save

### Expected result
Success

### Actual result
Warning
Invalid field: expiration_length
Invalid field: expiration_type

### System information (as much as possible)
Digicom 1.3.10

### Additional comments
This problem occurs after updating to Joomla 3.8.13

**Comment by shamsbd71** [comment]
Issue fixed.
