### ISSUE TITLE
Problem with product title in backend

### ISSUE THREAD

**Issue by betools** [themexpert/digicom#44]
When I try to create a new product, 'Title' field is not showing any text, but save correctly.
See in attached image, title field looks like in blank, but title is in it (only not visible during backend insert and edit)

![title_products_dont_show_backend](https://cloud.githubusercontent.com/assets/5460729/6880993/0ee13752-d52a-11e4-94a8-1d066a5f5318.jpg)

But title is correct in frontend:
![title_show_frontend](https://cloud.githubusercontent.com/assets/5460729/6880997/40e14be8-d52a-11e4-8a28-0757e3f76355.jpg)

**Comment by shamsbd71** [comment]
@codexpert 
please check the css, i checked it , its ok at my end

**Comment by codexpert** [comment]
@betools which browser you are using? Its ok here.

**Comment by betools** [comment]
I'm using Firefox 36.0.4 on a Windows 8.1 and tried several times, but problem persists. Cleaned cache, used some cleaning apps (CCleaner and TuneUp Utilities), but nothing changed - title is not visible.

If I open products list in admin, and click on a existent product to edit, same occurs - can't see title and alias of a product.

![product_title_firefox](https://cloud.githubusercontent.com/assets/5460729/6882393/bfce5694-d561-11e4-986d-0b02df9bc2ea.jpg)
 

In Google Chrome Version 41.0.2272.101 m (64-bit) this fields is OK. No problem with visualization.
Problem only affects Firefox only

**Comment by betools** [comment]
@codexpert  Problem in CSS, if I change padding values to a lower value (from 18px to 4px), I can see text in fields correctly - but overall looking is affected (more compact fields in height)

.form-title-alias .control-group .controls input[type="text"] {
    box-sizing: border-box;
    padding: 4px 10px;
    width: 100%;
}

**Comment by codexpert** [comment]
I've fixed it here have look https://github.com/themexpert/digicom/commit/c4cdfb520ac112f2364d4baa8fd96c849ff3b174

**Comment by betools** [comment]
@codexpert 

Perfect!
With padding: 10px and height: 100% works 100% OK now in Firefox!
