### ISSUE TITLE
ShoppingCart Module - problem if empty

### ISSUE THREAD

**Issue by betools** [themexpert/digicom#49]
If Cart Module has no products in frontend, it shows a button with a link 'shopping cart is empty', but when clicked, instead of goes to Digicom categories, it shows a error like images below:
![error_shoppingcart_module](https://cloud.githubusercontent.com/assets/5460729/6884319/4f7bff20-d5c2-11e4-8034-9565cb8b6ab5.jpg)

The frontend error when button is clicked:
![error_shoppingcart_module_clicked](https://cloud.githubusercontent.com/assets/5460729/6884320/64f299cc-d5c2-11e4-881c-b96127eb8af8.jpg)

**Comment by shamsbd71** [comment]
this was the issue with thumb create. when a product image has been deleted, then it was showing the error, its solved now, we ignored to create the thumb if img not exist
https://github.com/themexpert/digicom/commit/13cf85f8847b6a516a051f4b1f213317e3c9843f

**Comment by codexpert** [comment]
Done https://github.com/themexpert/digicom/commit/976a64b7cf3baf0cfdf60d66505e093424663a56
