### ISSUE TITLE
Customers and Transactions removing when cleaning data

### ISSUE THREAD

**Issue by betools** [themexpert/digicom#54]
Hi! I'm testing some things, and like to remove all test data I have used:
1 -  I remove all Joomla user
2 - I remove all transactions made in shop

But some data stills populate my graph dashboard, like Total Sale, Total Orders, and other stat infos. Same occur with Customers list, all Customers persists in list - but don't have Joomla users associated

![customer_dont_remove_clicked](https://cloud.githubusercontent.com/assets/5460729/6884524/d349ae1a-d5cc-11e4-8160-b426d280ef84.jpg)

When click on customer (with no user associated), I have no option to exclude this customer
![customer_dont_remove](https://cloud.githubusercontent.com/assets/5460729/6884521/c0fc4a42-d5cc-11e4-92c7-23d976419c87.jpg)

And stats persists in graph, even with no transactions (all deleted)
![sales_dont_remove](https://cloud.githubusercontent.com/assets/5460729/6884525/dd3c94a0-d5cc-11e4-81cd-5f4a04186941.jpg)

It is possible to clean all data?
Deleting users >> clean correspondent Customer
Deleting transaction >> remove it's value and stats from graphs and overall statistics

I think we have several cases we need to delete some person or clean some transaction... and in this case it's good if all sync

**Comment by codexpert** [comment]
@betools you are right. We've to change the way we are handling customer data. We are not saving there data right now to avoid duplication. We have to think a better way :+1:

**Comment by codexpert** [comment]
@betools after deleting all the orders you need to clear the order trash too. Deleted order goes to trash first.

**Comment by betools** [comment]
@codexpert  I can't see any place where trashed itens goes to...  in Orders screen, nothing is showing

see image file below, no options here to select or filter deleted transactions (like Joomla core articles do)
![orders_deleted](https://cloud.githubusercontent.com/assets/5460729/6887234/4c5b1412-d62f-11e4-9b25-dd98057937e9.jpg)

I have some different amounts showing in different places, but in really all stast must be equal to zero - I deleted (or tried) all past purchases

1 - before deletion I have 73500.0 BRL
2 - deleting all transactions is showing 1463.79 in dashboard main page 
3 - if I click on Reports tab, I see 20000.89 (I believe this tab is not fully implemented yet)

I can see in individual products that they store this info too, not clean deletion transaction stats
![reports_inproducts](https://cloud.githubusercontent.com/assets/5460729/6887248/c481b70c-d62f-11e4-9d3c-5a8c01b4b946.jpg)

**Comment by codexpert** [comment]
Ahhhh my bad, orders are not going to trash :(. You are right, will look into it.
