### ISSUE TITLE
Download page in frontend

### ISSUE THREAD

**Issue by betools** [themexpert/digicom#60]
Hi, I feel a bit confused when in Downloads page (frontend), some tabs with no content is in top of the products list,please see image with descriptions 

EDITED - Filename is showing all path - this is neccessary? I think showing only 'gpx-daily.zip' is better than exposing my folder structure 'digicom/files/gpx-daily.zip' to protect direct downloads

image 1 - 
![downloads_frontend](https://cloud.githubusercontent.com/assets/5460729/6887503/a6d9608a-d637-11e4-89b2-eaee91653e54.jpg)

**Comment by codexpert** [comment]
There is some garbage order record i found on the databse. I removed that its its working as expected. We will clean the quickstart package after this beta test.

**Comment by shamsbd71** [comment]
issue fixed
https://github.com/themexpert/digicom/commit/4d7f1272b1bb8e5f4616d32f757e2b336e3e66ea
https://github.com/themexpert/digicom/commit/53ab4bca98bbd7a04708a68315abb3dfdfc0058c
