### ISSUE TITLE
SEF implementation 

### ISSUE THREAD

**Issue by betools** [themexpert/digicom#71]
just installed public beta version, but found a problem >> products not showing in frontend

made a clean and fresh new Joomla install... installed Digicom released today (instalable component) and all looks great in backend.

but only categories is visible in frontend... can't see any products after clicking in categories

**Comment by shamsbd71** [comment]
hi @betools 
for #digicom we have 2 type of category view
1. Categories (Its for only a list/name of those categories and sub categories that you have selected in menu)
2. Category (It will show a description of category and list of items under it.)

can you please confirm that if there everything ok? if not can i see you test site or can get some screenshot?

thanks for using #digicom

**Comment by betools** [comment]
Yes - All configured in right way

Please look images:

image 1 - Categories in Backend
![categories_backend](https://cloud.githubusercontent.com/assets/5460729/6970551/8f96fabe-d94c-11e4-8e84-8eb8d3dbe6c9.jpg)

image 2 - products in backend
![products_backend](https://cloud.githubusercontent.com/assets/5460729/6970549/8354f6d4-d94c-11e4-8015-a598df14dc8c.jpg)

image 3 - categories in frontend
![categories_frontend](https://cloud.githubusercontent.com/assets/5460729/6970563/a5901a30-d94c-11e4-9f8c-0a4ac4beb0dd.jpg)

image 4 - products in frontend
![products_frontend](https://cloud.githubusercontent.com/assets/5460729/6970572/b66d0cdc-d94c-11e4-8320-3d071c42ef07.jpg)

**Comment by betools** [comment]
I forgot to mentionabout what type of menu I'm using.... see images:

image 1
![menu_type](https://cloud.githubusercontent.com/assets/5460729/6970710/9be904b4-d94d-11e4-9427-5a5da41b052d.jpg)

image 2
![menu_type2](https://cloud.githubusercontent.com/assets/5460729/6970714/a23d165c-d94d-11e4-9f71-8e4af98a9bea.jpg)

**Comment by betools** [comment]
Hi @shamsbd71 I have sended login infos and link to access admin of this test website to Parvez email... if you like I can create a new user for you have a look inside.

But I removed Joomla, made another fresh install, installed Digicom and put some categories and products inside... all looks good, except products page after selecting some categorie...

Same occur with module Digicom Categories in frontend... when clicked, not show products.
Products is Public, all are published and with correct settings...  I use Siteground, but it is the same enviroment of all tests in past week, before this beta public, with all working great before

**Comment by shamsbd71** [comment]
hello @betools 
i think i forget to tell: in this beta release we didnt implement SEF for DigiCom. Sorry for that :(

would you please try by turning SEF off from Joomla Global Configuration 
SEO Settings
 Search Engine Friendly URLs
  select "NO"

thanks

**Comment by betools** [comment]
thanks!   now it works!


(hope the SEO can be turned on in final releases...)

**Comment by codexpert** [comment]
Will do in Beta 2 :)
