### ISSUE TITLE
Duplicated menus in administration

### ISSUE THREAD

**Issue by betools** [themexpert/digicom#72]
I liked the dedicated menu to Digicom in administrator menu of Joomla.

But in Components, we have all Digicom buttons again...  for me is OK, but I think this can be a little confusing to new users/or newbie clients

(I don't know if this can be a bug, or the duplicate menu is normal in your layout admin project)

**Comment by shamsbd71** [comment]
Hi @betools 
thanks for the notice of this menu. basically me and @codexpert were discussed about this duplicacy before i create them. we are looking for users comment either to keep the regular one details as the dedicated one.

so let us know whats your choice :)

**Comment by betools** [comment]
I like more the dedicated one, very easy to show to our clients...    
I think dedicated is the best!
