### ISSUE TITLE
Missing string in the language file. Language files in admin and site en-GB are missing!

### ISSUE THREAD

**Issue by carosouza** [themexpert/digicom#81]
Missing string in the language file. Language files in admin and site en-GB are missing.

Missing string:
JGLOBAL_PRODUCT_ORDER_LABEL="?????"
JGLOBAL_PRODUCT_ORDER_DESC="?????"
COM_DIGICOM_PRODUCTS_LIST_PRODUCT_ORDER_FEATURED="???????"
Error
When choosing a menu item as a product and the strings above gives this error:
Warning: Header may not contain more than a single header, new line detected in C:\Ampps\www\joomla341\libraries\joomla\application\web.php on line 960

Warning: Cannot modify header information - headers already sent by (output started at C:\Ampps\www\joomla341\libraries\joomla\application\web.php:960) in C:\Ampps\www\joomla341\libraries\joomla\application\web.php on line 960

Warning: Cannot modify header information - headers already sent by (output started at C:\Ampps\www\joomla341\libraries\joomla\application\web.php:960) in C:\Ampps\www\joomla341\libraries\joomla\application\web.php on line 960

Tests in localhost

Thanks!!

**Comment by shamsbd71** [comment]
hi @carosouza 
thanks for your reports. but to solve it i need to know some more info
like the url of the error and the version you are using and if possible the screenshots.

we would be happy if you join in gitter chat or skype. thanks

**Comment by carosouza** [comment]
Hello, I did the tests again and is no longer appearing errors. Disregard thanks.
