### ISSUE TITLE
Error in Beta3

### ISSUE THREAD

**Issue by carosouza** [themexpert/digicom#88]

**Comment by carosouza** [comment]
Hello, I downloaded and installed beta3, but clicking to access the component (panel) gives the following error:

1146 - Ocorreu um erro.

Table 'joomla341.vv5zt_digicom_orders' doesn't exist SQL=SELECT o.*, c.firstname, c.lastname FROM vv5zt_digicom_orders o, vv5zt_digicom_customers c WHERE `c`.`id`=`o`.`userid` AND `status` = "Active" ORDER BY `o`.`order_date` DESC LIMIT 5

In Localhost
J341
PHP 5.5.19

Thanks

**Comment by codexpert** [comment]
Did you tried on fresh install or on top of existing DgiCom version? Fresh install works fine here and we already said it won't work on update http://www.themexpert.com/blog/digicom-beta-3-released-product-validity-customer-management-and-more

**Comment by shamsbd71** [comment]
thanks for the report, as we setup new relational table, it may cause on install and drop table event, we will check back that in next beta...

**Comment by carosouza** [comment]
Hello, Digicom has been installed on a version of Joomla 3.4.1 clean and complete!
